/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_brunjoy_jni_JNI */

#ifndef _Included_com_brunjoy_jni_JNI
#define _Included_com_brunjoy_jni_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_brunjoy_jni_JNI
 * Method:    a
 * Signature: ([BI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_brunjoy_jni_JNI_a
  (JNIEnv *, jclass, jbyteArray, jint);

/*
 * Class:     com_brunjoy_jni_JNI
 * Method:    b
 * Signature: (DDII)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_brunjoy_jni_JNI_b
  (JNIEnv *, jclass, jdouble, jdouble, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
