/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_brunjoy_Setting */

#ifndef _Included_com_brunjoy_Setting
#define _Included_com_brunjoy_Setting
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_brunjoy_Setting
 * Method:    set
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_com_brunjoy_Setting_set
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_brunjoy_Setting
 * Method:    setParam
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_brunjoy_Setting_setParam
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_brunjoy_Setting
 * Method:    getParam
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_brunjoy_Setting_getParam
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
