/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_brunjoy_jni_JNINet */

#ifndef _Included_com_brunjoy_jni_JNINet
#define _Included_com_brunjoy_jni_JNINet
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_brunjoy_jni_JNINet
 * Method:    setHost
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_brunjoy_jni_JNINet_setHost
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_brunjoy_jni_JNINet
 * Method:    setPort
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_brunjoy_jni_JNINet_setPort
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_brunjoy_jni_JNINet
 * Method:    doGet
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_brunjoy_jni_JNINet_doGet
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_brunjoy_jni_JNINet
 * Method:    doPost
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_brunjoy_jni_JNINet_doPost
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
